all_stars/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('about/',views.AboutPage.as_view(), name='about'),
    path('contact/',views.ContactPage.as_view(), name='contact'),
    # url('accounts/login/', auth_views.login, name='login'),
    # url('accounts/logout/', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    path('events/', include('events.urls', namespace='events')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from .views import *


app_name = 'events'

# urls down

urlpatterns = [
    path('', EventList.as_view(), name='all'),
    path('categories/', CategoryList.as_view(), name='categories'),
    path('categories/<category>/', CategoryEventsList.as_view(), name='category_events'),
    path('categories/<category>/<int:pk>/', event_detail, name='single'),
    path('search/events', SearchResultView.as_view(), name='search_results')
    # path('new/', views.EventCreate.as_view(), name='new_event'),
    # path('<int:pk>/edit/',views.EventUpdate.as_view(), name='update'),
    # path('<int:pk>/remove',views.EventDelete.as_view(), name='delete'),
    # path('categories/<category>/<int:pk>/comment/new', new_comment, name='new_comment'),
    # path('/comment/<int:pk>/remove', views.CommentDelete.as_view(),name='delete')

]

events/models.py
from django.db import models
# from django.contrib.auth import get_user_model
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse



# User = get_user_model()
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=20)
    # slug = models.SlugField(allow_unicode=True,unique=True,blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to ='images',blank=True)

    def __str__(self):
        return self.name

    # def save(self,*args,**kwargs):
    #     self.slug = slugify(self.name)
    #     super().save(*args,**kwargs)

class Event(models.Model):
    # user = models.ForeignKey(User)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    summary = models.TextField()
    release_date = models.DateField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


    # def get_absolute_url(self):
    #     return reverse('events:single', kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    event = models.ForeignKey(Event,on_delete=models.CASCADE, related_name='comments')
    # user = models.ForeignKey(User)
    name = models.CharField(max_length=20)
    email_adress = models.EmailField()
    body = models.TextField()
    created_date = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('events:single', kwargs={'pk':self.event.pk})


class EventImage(models.Model):
    event = models.ForeignKey(Event,on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to ='images')

    def __str__(self):
        return self.event.title + ' image'

class EventVideo(models.Model):
    event = models.ForeignKey(Event,on_delete=models.CASCADE, related_name='videos')
    video = models.FileField(upload_to ='videos')

    def __str__(self):
        return self.event.title + ' video'

events/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email_adress', 'body')

all_stars/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class AboutPage(TemplateView):
    template_name='about.html'

class ContactPage(TemplateView):
    template_name ='contact.html'

events/views.py
from django.shortcuts import render
from django.views.generic import (CreateView,UpdateView,ListView,DetailView,DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import *
from django.urls import reverse_lazy
from braces.views import SelectRelatedMixin
from django.shortcuts import get_object_or_404, render,redirect
from .forms import CommentForm
from .filters import  EventFilter
from django.db.models import Q

# Create your views here.

# Events view:

class CategoryList(ListView):
    model = Category


class CategoryEventsList(ListView):
    template_name = "events/category_events_list.html"

    def get_queryset(self):
        self.category = get_object_or_404(Category, name=self.kwargs['category'])
        return Event.objects.filter(category=self.category)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())
        return context

class EventList(ListView):
    model = Event

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())
        return context

class SearchResultView(ListView):
    model = Event
    template_name = 'events/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Event.objects.filter(
        Q(title__contains=query) | Q(summary__contains=query)
        )
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context

# class EventCreate(CreateView,LoginRequiredMixin):
#     model = Event
#     fields = ('title','text','image')

# class EventUpdate(UpdateView,LoginRequiredMixin):
#     model = Event
#     fields = ('title','text','image')

# class EventDelete(DeleteView,LoginRequiredMixin):
#     model = Event
#     success_url = reverse_lazy('events:all')


#
# class EventDetail(DetailView):
#     model = Event
#
# def new_comment(request, pk, category):
#     event = get_object_or_404(Event,pk=pk)
#     # Comment posted
#     if request.method == 'POST':
#         comment_form = CommentForm(data=request.POST)
#         if comment_form.is_valid():
#
#             # Create Comment object but don't save to database yet
#             comment = comment_form.save(commit=False)
#             # Assign the current post to the comment
#             comment.event = event
#             # Save the comment to the database
#             comment.save()
#             return redirect('events:single', pk=pk, category=category)
#     else:
#         comment_form = CommentForm()
#
#     return render(request, 'events/comment_form.html', {'comment_form': comment_form})



def event_detail(request, pk, category):
    template_name = 'event_detail.html'
    event = get_object_or_404(Event, pk=pk)

    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            comment.event = event
            # Save the comment to the database
            comment.save()

            return redirect('events:single', pk=pk, category=category)

    else:
        comment_form = CommentForm()

    return render(request, 'events/event_detail.html', {'event': event,
                                           'comment_form': comment_form})

# class  CommentDelete(DeleteView,LoginRequiredMixin):
#     model = Comment
#     success_url = reverse_lazy('events:single')

events/templates/events/category_events_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<form method="GET">
  {{filter.form|crispy}}
  <button type="submit" class="btn btn-info">Filter</button>
</form>
<br>
 <div class="row">
 {% for event in filter.qs %}
   <div class="col-lg-4 col-md-6 col-12">
       <div class="card" style="width: 18rem;">
        <img src="{% static 'events/images/allstars.jpg' %}" class="card-img-top" alt="event image">
        <div class="card-body">
          <h5 class="card-title">{{event.title}}</h5>
          <p class="card-text">{{event.summary}}</p>
          <a href="{% url 'events:single' category=event.category.name pk=event.pk %}" class="btn btn-primary">Event detail</a>
        </div>
      </div>
      <br>
   </div>
 {% endfor %}
 </div>
 {% endblock %}

events/templates/events/category_list.html
{% extends "base.html" %}
{% load static %}
 {% block content %}
 <div class="row">
 {% for category in category_list %}
   <div class="col-lg-4 col-md-6 col-12">
       <div class="card" style="width: 18rem;">
        <img src="{% static 'events/images/allstars.jpg' %}" class="card-img-top" alt="event image">
        <div class="card-body">
          <h5 class="card-title">{{category.name}}</h5>
          <p class="card-text">{{category.description}}</p>
          <a href="{% url 'events:category_events' category=category.name %}" class="btn btn-primary">Events <span class="badge badge-light">{{ category.event_set.count }}</span></a>
        </div>
      </div>
      <br>
   </div>
 {% endfor %}
 </div>
 {% endblock %}

events/templates/events/event_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="myevent">
  <strong><h1>{{event.title}}</h1></strong>
  <h5>{{event.body}}</h5>
  <h2>Gallery:</h2>
  {% for im in event.images.all %}
    <img src="{{im.image.url}}" class="rounded img-fluid myimg" alt="Responsive image">
  {% empty %}
    <p>No images posted.</p>
  {% endfor %}

  {% for vid in event.videos.all %}
  <video width="320" height="240" controls>
    <source src="{{vid.video.url}}" type="video/mp4">
    <source src="{{vid.video.url}}" type="video/ogg">
    Your browser does not support the video tag.
  </video>
  {% empty %}
    <p>No videos posted.</p>
  {% endfor %}
  <p>{{event.created_date}}</p>
</div>


<hr>
{% for comment in event.comments.all %}
 <h5>User: {{comment.name}}</h5>
 <h5>Email Adress:{{comment.email_adress}}</h5>
 <p>Comment: {{ comment.body | linebreaks }}</p>
{% empty %}
    <p>No comments posted.</p>
 {% endfor %}
 <hr>

  <form method="post" style="margin-top: 1.3em;">
    {{ comment_form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
  </form>

{% endblock %}

events/templates/events/event_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
 {% block content %}
<form method="GET" class="myform">
     {{filter.form|crispy}}
   <button type="submit" class="btn btn-outline-info">Filter</button>
</form>
<br>
 <div class="row">
 {% for event in filter.qs %}
   <div class="col-lg-4 col-md-6 col-12">
       <div class="card" style="width: 18rem;">
        <img src="{% static 'events/images/allstars.jpg' %}" class="card-img-top" alt="event image">
        <div class="card-body">
          <h5 class="card-title">{{event.title}}</h5>
          <p class="card-text">{{event.summary}}</p>
          <a href="{% url 'events:single' category=event.category.name pk=event.pk %}" class="btn btn-primary">Event detail</a>
        </div>
      </div>
      <br>
   </div>
 {% endfor %}
 </div>
 {% endblock %}

events/templates/events/search_results.html
{% extends "base.html" %}
{% load static %}
{% load highlight_tags %}
{% load crispy_forms_tags %}
 {% block content %}
 <div class="row">
 {% for event in event_list %}
   <div class="col-lg-4 col-md-6 col-12">
       <div class="card" style="width: 18rem;">
        <img src="{% static 'events/images/allstars.jpg' %}" class="card-img-top" alt="event image">
        <div class="card-body">
          <h5 class="card-title">{{ event.title|highlight:q }}</h5>
          <p class="card-text">{{ event.summary|highlight:q }}</p>
          <a href="{% url 'events:single' category=event.category.name pk=event.pk %}" class="btn btn-primary">Event detail</a>
        </div>
      </div>
      <br>
   </div>
 {% endfor %}
 </div>
 {% endblock %}

templates/about.html
{% extends "base.html" %}

{% block content %}
  <h1>About us</h1>



  <section id='team'>
    <h1>About our team</h1>
    <p class='lead'>Lorem ipsum dolor sit amet</p>

    <p>consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


</section>


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<section id='vision'>
  <h1>About our vison</h1>
  <p class='lead'>Lorem ipsum dolor sit amet</p>

  <p>consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ALL STARS</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Local csss file -->
  <link rel="stylesheet" href="{% static 'events/css/master.css'%}">


  </head>
  <body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'events/images/brand.png' %}" width="30" height="30" alt="can't load" loading="lazy">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'events:categories' %}">Categories <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'events:all' %}">Events <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url 'about' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              About us
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'about' %}">Our Team</a>
              <a class="dropdown-item" href="{% url 'about' %}">Our Vision</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'contact' %}">Contact Us</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'events:search_results' %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="mybody">
      {% block mycarousel %}{% endblock %}
      <div id="content">{% block content %}{% endblock %}</div>
    </div>

   <footer>
  Phone: <br> Email: <br>  lamo: </footer>

<!-- <canvas id="canvas"></canvas> -->

  </body>
  <script src="{% static "events/js/master.js"%}" type="text/javascript" ></script>
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

<h1>contact us</h1>
<h4>+0000000000000</h4>



{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block mycarousel %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 cimg" src="{% static "events/images/lmao.jpg" %}" alt="First slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>1536 x 600</h5>
        <p>Subtitle</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 cimg" src="{% static "events/images/lmao.jpg" %}" alt="Second slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>1536 x 600</h5>
        <p>Subtitle</p>
      </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 cimg" src="{% static "events/images/lmao.jpg" %}" alt="Third slide">
      <div class="carousel-caption d-none d-md-block">
        <h5>1536 x 600</h5>
        <p>Subtitle</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock %}

{% block content %}

<h1>Welcome To All Stars Page!</h1>

<h4>All Stars is a youth organization, dedicated towards connecting the youth and together with them, bring events, ranging from everything, including sports, education, charity and who can forget, entertainment, to life.
</h4>
{% endblock %}